---
title: "all_models_30year_summary_stats"
author: "Annemarie Eckes-Shephard"
date: "2025-03-14"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
classoption: landscape
---

tables that have to be compiled for the supplementaries, in word format.

```{r installDGVMTOOLS, eval=TRUE}

library(devtools)
#install_github("MagicForrest/DGVMTools")
library("DGVMTools")
```

```{r source_DBEN_helper_functions_other_setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

base.path <- "./"

Figs_dir <- paste0(base.path,"/../Figs/")

source(paste0(base.path,"/Format-DBEN_Eckes-Shephard_et_al2025.R"))
source(paste0(base.path,"/DBEN_helper_functions_clean.R"))

obs.path <-paste0(base.path,"/../observations/2_processed/")

```

only used to create table for supplementary materials in word-document format. The data is created within Eckes-Shephard_et_al2025.Rmd

```{css, echo = FALSE}
.verysmall .table{
      font-size: 6px;
}
```
    
\tiny 
    
```{r setup, include=TRUE}

load("../model_outputs/all_models_30year_summary_stats.RData")

options(knitr.kable.NA = "-") 
knitr::kable(FULL,caption = "Forest Carbon and dynamics variables summarised across the first 30 years of regrowth and equilibrium. Aboveground woody carbon (AGcwood, KgC m2) after 30 years of disturbance recovery, and at equilibrium, by model and site. WBgrowth fluxes and cmort rates (%) minimum and maximum rates within the first 30 years, and the minimum and maximum across models across these years. No model output marked by -", digits=2, cex=0.3)
```

```{r table}
#Upper and lower simulation year 
# similar content to chunk select_equilibrium_period in main manuscript

# reported in Table S1.5
# for some calculations, the model-specific dynamic equilibrium period after regrowth has finished is required
# the values are derived by eyeballing the timeseries of cwood variable for each model, and
# visually determining when an equilibrium has emerged.
# (i.e.changes in cwood are marginal or the amplitude size repeats itself.)
# note that I have been advised to use CABLE-POP years 1:30, as disturbance is more prevalent in the years 1:30 and contribute to a large variability, that is landscape-scale.

eq_values_FIN <- data.frame(lower=rep(NA,9))
eq_values_FIN$lower  <- c(200, 300,   150 ,320,   320 ,  600, 715, 300  , 500)
eq_values_FIN$upper  <- c(420,  450,   320, 450,   450,   900,  810,  420,   530)
eq_values_FIN$model  <- models_avail

eq_values_BIA        <- data.frame(lower=rep(NA,9))
eq_values_BIA$lower  <- c(200, 300 ,  150, 320 ,  320  , 600 ,700 ,240 ,  500)
eq_values_BIA$upper  <- c(420, 450 , 320, 450,  450,  900, 810, 450 , 530)
eq_values_BIA$model  <- models_avail


eq_values_BCI        <- data.frame(lower=rep(NA,9))
eq_values_BCI$lower  <- c(150, 250,  150, 320 ,  320  , 600, 500 ,  100  , 500) #LSM_DVM_comp$BCI$lower[1:lgth] # LPJG: 420 CABLE-POP: 1
eq_values_BCI$upper  <- c(420 ,450 , 320 ,450 , 450 , 900 ,810 , 450,  530) #LSM_DVM_comp$BCI$upper[1:lgth]# LPJG: 864 CABLE-POP: 30
eq_values_BCI$model  <- models_avail

eq_values <- list(eq_values_FIN,eq_values_BIA,eq_values_BCI)
names(eq_values) <- sites

#####################
#for manuscript:
eq_values_FIN$site <- "FIN"
eq_values_BIA$site <- "BIA"
eq_values_BCI$site <- "BCI"
eq_values_table <- rbind(eq_values_FIN,eq_values_BIA,eq_values_BCI)

knitr::kable(eq_values_table[order(eq_values_table$model),], caption="Upper and lower simulation year that make up the period from which each model is considered in equilibrium. Some models were run for a longer timeperiod than the prescribed 450 years in order to achieve a mature forest in equilibrium state.", col.names = NULL) 

```


Deviations: ORCHIDEE: AGcwood
```{r Supplementary_Materials_benchmarking_self_thinning,eval=TRUE}

# Self-thinning relationships should ideally be performed on Aboveground woody carbon (AGcwood), as is done in the observations, but we only have AGcwood output as total or per PFT.
# we could apply a factor on cwood_size, but a universal conversion factor on all models may be unfair, especially here, where allometry might have mattered in creating self-thinning behaviour in the model. So it is cleaner to stay with cwood_size, also for the mean individual biomass calculation that goes into the self-thinning slope creation.
# mortality rates are derived using total woody carbon (cwood) and total /a specific mortality woody carbon flux, because we consider more than AGcwood in the wood morality fluxes using AGcwood would bias the rates.

# using variables outputted by size-classes, we can also remove the smallest trees from the analysis, which are normally not accounted for in datasets used for self-thinning analysis (?!?!?!?)

# remember: the observations have been filtered for trees >10 dbh, and stand age > 10.

#now, to the same but plot all models in one plot:
#pdf(file=paste0(Figs_dir,simdate,"/Supplementary_materials_4_Benchmark_self_thinning_all_models_point_selection_methods_3plots.pdf"))

par(mfrow=c(4,3))
xlim_set = c(0,4)
ylim_set = c(-8,0)
point_cex = 0.4
sites <- c("FIN","BIA","BCI")

#plot.new()

#plot.new()

xmax = 410-33 # only do analysis on the original simulation length. Longer simulation periods mean that the selection of the 95th percentile (if applicable) of the mortality rate has a larger number of points to choose from, and also additional equilibrium forest dynamics that blurr the picture (especially in LPJG)
#-33 because the equilibrium period is already subtracted.

#legend("center",legend=c( "self-thinning line","self-thinning period","output variable(s)"),lty=c(1,NA,NA), pch=c(NA,1,1), col=c("blue","red","black"))

#plot.new()

#legend("center",legend=c("method 1) > 95% thinning mort", "method 2) > 95% total mort",  "method 3) autoadjusted", "method 4) manually adjusted"), col=rep("white",3),cex=0.8, lty=c(1,1,1))

#data frame where I collect the manually adjusted upper and lower boundary of the indexes to derive the self-thinning line.


manual_adjustment = data.frame(models_avail =rep(x = models_avail,each=3), site = rep(sites,length(models_avail)))
manual_adjustment$upper <- NA
manual_adjustment$lower <- NA
manual_adjustment_empty <- manual_adjustment

manual_adjustment$mort_rate_name <- NA
manual_adjustment$identification_method <- NA


#EDv3

adjust_EDv3=FALSE


 manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "BCI"),]$upper <- as.numeric(55)#as.numeric(467) # period with peak nstem numbers
  manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "BCI"),]$lower <- as.numeric(31)#as.numeric(400)
  manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "BCI"),]$identification_method <- "4"

if(isTRUE(adjust_EDv3)){
  manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "BIA"),]$upper <- as.numeric(467) # upper boundary
  manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "BIA"),]$lower <- as.numeric(400)
  manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "BIA"),]$identification_method <- "4"
   manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "FIN"),]$upper <- as.numeric(110)#as.numeric(467) # upper boundary
  manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "FIN"),]$lower <- as.numeric(32)#as.numeric(400)
  manual_adjustment[which(manual_adjustment$models_avail == "EDv3"
                          & manual_adjustment$site == "FIN"),]$identification_method <- "4"

}



#ORCHIDEE
  mansel=FALSE

if(mansel){ # not used in paper:
    manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "FIN"),]$upper <-  as.numeric(410)#as.numeric(150) #as.numeric(450) # upper boundary
manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "FIN"),]$lower <-  as.numeric(4)#as.numeric(50) #as.numeric(70)
manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "FIN"),]$identification_method <- "4" # manual adjustment
manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "BIA"),]$upper <-  as.numeric(20)#as.numeric(50) # upper boundary
manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "BIA"),]$lower <- as.numeric(1)# as.numeric(150)
manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "BIA"),]$identification_method <- "4" # manual adjustment
manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "BCI"),]$upper <-  as.numeric(10)#as.numeric(100)
manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "BCI"),]$lower <-  as.numeric(1)#as.numeric(60)
manual_adjustment[which(manual_adjustment$models_avail == "ORCHIDEE"
                        & manual_adjustment$site == "BCI"),]$identification_method <- "4" # manual adjustment
}


#SEIB-DGVM

#FIN: 50:80
#BIA: self-thinning. between sim year  41 :70
#BCI self-thinning:  31:50# done
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "BCI"),]$upper <- as.numeric(25) # 25 # upper boundary 231
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "BCI"),]$lower <- as.numeric(10) #8#32
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "BCI"),]$identification_method <- "4" # manual adjustment
#SEIB-DGVM
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "FIN"),]$upper <- as.numeric(100) #150 upper boundary 231
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "FIN"),]$lower <- as.numeric(50) ##32
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "FIN"),]$identification_method <- "4" # manual adjustment
#SEIB-DGVM
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "BIA"),]$upper <- as.numeric(150) # 150# upper boundary 231
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "BIA"),]$lower <- as.numeric(41) #90#32
manual_adjustment[which(manual_adjustment$models_avail == "SEIB-DGVM"
                        & manual_adjustment$site == "BIA"),]$identification_method <- "4" # manual adjustment

#FATES
manual_adjustment[which(manual_adjustment$models_avail == "FATES"
                        & manual_adjustment$site == "FIN"),]$upper <- as.numeric(290) # upper boundary 231
manual_adjustment[which(manual_adjustment$models_avail == "FATES"
                        & manual_adjustment$site == "FIN"),]$lower <- as.numeric(115) #32


#JULES-RED
#manual_adjustment[which(manual_adjustment$models_avail == "JULES-RED" & manual_adjustment$site == "FIN"),]$lower <- as.numeric(105)
#manual_adjustment[which(manual_adjustment$models_avail == "JULES-RED" & manual_adjustment$site == "FIN"),]$upper <- as.numeric(200)
manual_adjustment[which(manual_adjustment$models_avail == "JULES-RED" & manual_adjustment$site == "BIA"),]$lower <- as.numeric(55)
manual_adjustment[which(manual_adjustment$models_avail == "JULES-RED" & manual_adjustment$site == "BIA"),]$upper <- as.numeric(131)
manual_adjustment[which(manual_adjustment$models_avail == "JULES-RED" & manual_adjustment$site == "BIA"),]$identification_method <- "4" # manual adjustment

#manual_adjustment[which(manual_adjustment$models_avail == "JULES-RED" & manual_adjustment$site == "BCI"),]$lower <- as.numeric(50)
#manual_adjustment[which(manual_adjustment$models_avail == "JULES-RED" & manual_adjustment$site == "BCI"),]$upper <- as.numeric(131)

#manual_adjustment[which(manual_adjustment$models_avail == "BiomeEP" & manual_adjustment$site == "BIA"),]$lower <- as.numeric(190)
#manual_adjustment[which(manual_adjustment$models_avail == "BiomeEP" & manual_adjustment$site == "BIA"),]$upper <- as.numeric(220)
#manual_adjustment[which(manual_adjustment$models_avail == "BiomeEP" & manual_adjustment$site == "BIA"),]$identification_method <- "4" # manual adjustment


for(site in sites){

 #prepare dataframe that collects slopes and intercepts
 collect_stl <- data.frame(Mname=models_avail,STLslope =NA,STLint =NA,site= site)

  for (model_name in models_avail){
   #call model:
    # 1) call model
    # 2) update the "Total " value, since that is the total for all sizeclasses, but we exclude sizeclasses in indeces 4-6, below 10 dbh,
    # as this is often done in self-thinning studies.
    # 3) directly convert to dataframe, for easier to access data.
    MODEL_nstem   <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                                    var="nstem_size",model_name=model_name, co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]))

    #update to default simulation length -is model specific:
    xmax <- length(MODEL_nstem$Total)
    MODEL_nstem <-  MODEL_nstem[1:xmax,]

    if(model_name=="ORCHIDEE"){
      var="cwood_size"
      MODEL_agcwood <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                                    var=var,model_name= model_name, co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]))

      #update to default simulation length as per protocol:
      MODEL_agcwood <-  MODEL_agcwood[1:xmax,]
    }else{
      var="cwood_size"
      MODEL_agcwood <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                                    var=var,model_name= model_name, co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]))
      #update to default simulation length as per protocol:
      MODEL_agcwood <-  MODEL_agcwood[1:xmax,]
    }

    #LPJ-GUESS and FATES have a collection of mortality mechanisms that go beyond self-thinning,
    # e.g. _age(LPJ-GUESS) or _termination(FATES), and they lie somewhat outside the conventional self-thinning relationship.
    if(model_name=="LPJ-GUESS"){
      MODEL_mort_greff <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                                   var="cmort_greff",model_name=model_name,co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]))

      #update to default simulation length
      MODEL_mort_greff <-  MODEL_mort_greff[1:xmax,]

      #as percentage of total stand, and adhere to object type for subsequent use:
      MODEL_mort <- data.frame(Year=MODEL_mort_greff$Year, Total = rep(NA,length(MODEL_mort_greff$Total)))
      MODEL_mort$Total  <- calc_mort_rate_andrusetal2021(MODEL_mort_greff$Total,MODEL_agcwood$Total)
      MODEL_mort$Total  <- MODEL_mort_greff$Total #calc_mort_rate_andrusetal2021(MODEL_mort_greff$Total,MODEL_nstem$Total)
      # MODEL_mort = NULL
      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$identification_method <- "1"
      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$mort_rate_name <- "greff"

    }else if(model_name =="FATES" & site != "FIN"){ #manual selection for FIN
      MODEL_mort <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                     var="stemmort_cstarv",model_name=model_name,co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]))
     #MODEL_mort = NULL

      #update to default simulation length
      MODEL_mort <-  MODEL_mort[1:xmax,]

      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$identification_method <- "1"
      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$mort_rate_name <- "cstarv"


    }else if(model_name =="CABLE-POP"){
      # we cannot separate this by sizeclass, which is a bit problematic, but maybe it works anywyas, to show the crowding mechanism.
      MODEL_mort_crowd <- as.data.frame(get_model_output(site=site, run="P0",
                                     var="cmort_crowd",model_name=model_name,co2_levels = "412ppm")@data[-c(1:33),])

      # update to default simulation length
      MODEL_mort_crowd <-  MODEL_mort_crowd[1:xmax,]
      # as percentage of total stand, and adhere to object type for subsequent use:
      MODEL_mort        <- data.frame(Year = MODEL_mort_crowd$Year, Total = rep(NA,length(MODEL_mort_crowd$Total)))
      MODEL_mort$Total  <- MODEL_mort_crowd$Total #calc_mort_rate_andrusetal2021(MODEL_mort_crowd$Total,MODEL_agcwood$Total)
      # MODEL_mort = NULL

      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$identification_method <- "1"
      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$mort_rate_name <- "crowd"
    }else if(model_name =="EDv3" & site != "BCI"){ # manual adjustment at BCI

      MODEL_mort_size <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                     var="cmort_mort",model_name=model_name,co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]) )

      MODEL_mort_size <-  MODEL_mort_size[1:xmax,]

      #as percentage of total stand, and adhere to object type for subsequent use:
      MODEL_mort        <- data.frame(Year = MODEL_mort_size$Year, Total = rep(NA,length(MODEL_mort_size$Total)))
      MODEL_mort$Total  <- calc_mort_rate_andrusetal2021(MODEL_mort_size$Total,MODEL_agcwood$Total)

      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$identification_method <- "2"
      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$mort_rate_name <- "total"

      }else if(model_name =="BiomeE-Standalone" & site!="BIA"){
      #testing BiomeE-Standalone mortality rate ( does not distinguish between mortality rates, so probably not a good selector here?)
      #Actually: mortality rate seems to be a good selector, at least for BiomeE-Standalone ( more scattered for BiomeEP), but we cannot be 100% sure that this  mortality rate (potentially containing lots of other mortality processes besides self-thinning) indeed is dominated by self-thinning mortality.
      MODEL_nstem_size <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                     var="cwood_size",model_name=model_name,co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]) )
      MODEL_nstem_size <- MODEL_nstem_size[1:xmax,]
      MODEL_mort_size <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                     var="cmort_size",model_name=model_name,co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]) )
      #update to default simulation length as per protocol:
      MODEL_mort_size <-  MODEL_mort_size[1:xmax,]

      #as percentage of total stand, and adhere to object type for subsequent use:
      MODEL_mort        <- data.frame(Year = MODEL_mort_size$Year, Total = rep(NA,length(MODEL_mort_size$Total)))
      MODEL_mort$Total  <- calc_mort_rate_andrusetal2021(MODEL_mort_size$Total,MODEL_nstem_size$Total)

      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$identification_method <- "2"
      manual_adjustment[which(manual_adjustment$models_avail==model_name & manual_adjustment$site==site),]$mort_rate_name <- "total"
    }else{
      MODEL_mort = NULL
      # method 3, semiautomatical choice of self-thinning.
    }

    #plot entire timeseries of model in "self thinning space"
   # plot(log10(MODEL_nstem$Total),log10(MODEL_agcwood$Total/MODEL_nstem$Total),
  #          ylim=ylim_set,xlim=xlim_set,cex=point_cex,type="l",
  #  ylab="log(mean indiv. cwood) (KgC/m2)",xlab="log(nstem) (indiv/ha)", col="black")


    # not the entire regrowth period simulation is subject to self-thinning mechanisms,
    # must subset for the time where self thinning occurs, before fitting.
    # Here, I show what datapoints will be used in the thinning period

    # the slope:
    MODEL <- identify_thinning_period(agcwood = MODEL_agcwood$Total,
                            nstem=MODEL_nstem$Total,add_plot=FALSE,cmort=MODEL_mort$Total,
                            manual_adjustment[which(manual_adjustment$models_avail == model_name
                            & manual_adjustment$site == site),],model_name=model_name, site=site)
    MODEL_plot <- MODEL # for plotting later

    ############ ############ ############ ############ ############ ############
    ##rm some outliers which the different automatised approaches could not catch:

     if(site=="BIA" & model_name=="BiomeEP"){ #
      timepoints_rm_BIOMEEP = c(96:MODEL$time[length(MODEL$time)])
      MODEL_plot <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]# select only the first self-thinning period, the algorithm caught too many.
      MODEL <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
     }

     # select only the first self-thinning period, the algorithm caught small incedences following regrowth.
      if( model_name=="LPJ-GUESS"){ #
      timepoints_rm_BIOMEEP = c(120:MODEL$time[length(MODEL$time)])
      MODEL_plot <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
      MODEL <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
      }

      # select only the first self-thinning period, the algorithm caught small incedences following regrowth.
      if( model_name=="FATES" & site !="FIN"){ # FIN is manually selected
      timepoints_rm_BIOMEEP = c(120:MODEL$time[length(MODEL$time)])
      MODEL_plot <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
      MODEL <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
      }

       # select only the first self-thinning period, the algorithm caught small incedences following regrowth.
      if( model_name=="EDv3"& site=="BIA"){ #
      timepoints_rm_BIOMEEP = c(100:MODEL$time[length(MODEL$time)])
      MODEL_plot <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
      MODEL <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
      }

        # select only the first self-thinning period, the algorithm caught a longer stretch incedences following canopy closure
      if( model_name=="BiomeE-Standalone"& site=="BIA"){ #
      timepoints_rm_BIOMEEP = c(119:MODEL$time[length(MODEL$time)])
      MODEL_plot <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
      MODEL <- MODEL[which(!(MODEL$time %in% timepoints_rm_BIOMEEP)),]
      }
    ############ ############ ############ ############ ############ ############

    ##fit the self-thinning line:
    m <- lm(MODEL[,2:1])
   # points(MODEL[c(1,2)],col="red")

    collect_stl[which(collect_stl$Mname==model_name),]$STLslope <- m$coefficients[2]
    collect_stl[which(collect_stl$Mname==model_name),]$STLint   <- m$coefficients[1]

    #report on slope and method used to derive slope:
   # mtext(paste("st-slope=", round(m$coefficients[2],digits = 3)),side=3 )

    #add self-thinning line to graph
   # abline(lm(MODEL[,2] ~ MODEL[,1]),col= "blue" )


    #add information on whether the data points were  manually adjusted before creating the self-thinning line:
    if(is.na(manual_adjustment[which(manual_adjustment$models_avail == model_name
                           & manual_adjustment$site == site),]$identification_method)){
    # everything that is at this stage not categoriesed at the end was automatically adjusted (step 4).
    manual_adjustment[which(manual_adjustment$models_avail == model_name & manual_adjustment$site == site),]$identification_method <- "3"
    }
    n = manual_adjustment[which(manual_adjustment$models_avail == model_name & manual_adjustment$site == site),]$identification_method
    #report on slope and method used to derive slope:
   # mtext(side=3,line=-4, paste("method",n))


    if(!is.null(MODEL_mort)){
      # fit the timeseries with the selected period:
      idx <- MODEL_plot$time
     # plot(MODEL_mort$Year,MODEL_mort$Total, ylab= "mortality rate (% /yr)", xlab="year", main=paste(model_name,site))
     # points(MODEL_mort[idx,]$Year, MODEL_mort[idx,]$Total,col="red")

      #to later calculate the self-thinning period length:
      lgth <- length(idx)
      manual_adjustment[which(manual_adjustment$models_avail == model_name & manual_adjustment$site == site),]$upper <- idx[lgth]
      manual_adjustment[which(manual_adjustment$models_avail == model_name & manual_adjustment$site == site),]$lower <- idx[1]

    }
    #for those models with manual adjustment, create the mortality timeseries here and then plot:
    if(is.null(MODEL_mort)){
       # retrieve timeseries now, for diagnosing where self-thinning points lie:
      if(model_name=="JULES-RED"){
      MODEL_mort_size <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                                    var="stemmort",model_name= model_name, co2_levels = "412ppm")@data[-c(1:33),-c(4:5)]))
      MODEL_mort_size <-  MODEL_mort_size[1:xmax,]

      }else if(model_name =="BiomeEP"){

         MODEL_mort_size <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                                    var=var,model_name= model_name, co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]))
      MODEL_mort_size <-  MODEL_mort_size[1:xmax,]

      } else {
      # MODEL_mort_size <- as.data.frame(update_total(get_model_output(site=site, run="P1",
       #                                             var="stemmort",model_name= model_name, co2_levels = "412ppm")@data[-c(1:33),-c(4:6)]))
        if(model_name=="EDv3"){ var= "cmort_mort"}else{ var = "cmort"}
       MODEL_mort_size <- as.data.frame(update_total(get_model_output(site=site, run="P0",
                                                    var=var,model_name= model_name, co2_levels = "412ppm")@data[-c(1:33),]))

      #update to default simulation length as per protocol:
      MODEL_mort_size <-  MODEL_mort_size[1:xmax,]

      }

      #as percentage of total stand, and adhere to object type for subsequent use:
      MODEL_mort        <- data.frame(Year = MODEL_mort_size$Year, Total = rep(NA,length(MODEL_mort_size$Total)))
      MODEL_mort$Total  <- calc_mort_rate_andrusetal2021(MODEL_mort_size$Total,MODEL_nstem$Total)
      # fit the timeseries with the selected period:
      idx <- MODEL_plot$time
    #  plot(MODEL_mort$Year,MODEL_mort$Total, ylab= "mortality rate (%  /yr)", xlab="year", main=paste(model_name,site))
    #  points(MODEL_mort[idx,]$Year, MODEL_mort[idx,]$Total,col="red")

      #to later calculate the self-thinning period length:
      lgth <- length(idx)
      manual_adjustment[which(manual_adjustment$models_avail == model_name & manual_adjustment$site == site),]$upper <- idx[lgth]
      manual_adjustment[which(manual_adjustment$models_avail == model_name & manual_adjustment$site == site),]$lower <- idx[1]

    }


    # plot the timeseries with the selected period:
    idx <- MODEL_plot$time

   # plot(MODEL_agcwood$Year,MODEL_agcwood$Total, ylab= "cwood (KgC/m2)", xlab="year")
   # points(MODEL_agcwood[idx,]$Year, MODEL_agcwood[idx,]$Total,col="red")
   # legend("bottomright",legend=c("self-thinning period"),fill="red")

   rm(MODEL_mort) # reset to null, so that the thinning period can be correctly identified and the automated plots work in that function.
  #}

 collect_stl$site <-site
 collect_stl$co2 <- "412ppm"

  }
   #collect site-specific records, bring together ambient records:
     if(site=="FIN"){
      collect_final <- rbind(collect_stl)
     }else{
      coll  <- rbind(collect_stl)
      collect_final <- rbind(collect_final,coll)
     }

}

#mtext(side=2, "log(mean individual biomass)",line=,outer=TRUE)
#mtext(side=1,"log(nstem)",outer=TRUE,line=1)
#dev.off()

# the mean ensemble time to self-thinning (because of the PPA approach,
# this does not necessarily correspond to closed-canopy,
# but it will be used in the conceptual diagram in the manuscript
# as anchor point for the timings
# mean(report_self_thinning[which(report_self_thinning$site=="BCI"),]$lower)
#29.44444
#mean(report_self_thinning[which(report_self_thinning$site=="BIA"),]$lower)
#39.55556
#mean(report_self_thinning[which(report_self_thinning$site=="FIN"),]$lower)
#52.77778


#in-text reporting of self-thinning durations:
#max(report_self_thinning[which(report_self_thinning$site=="BCI"& report_self_thinning$Model!="ORCHIDEE"),]$duration)

#max(report_self_thinning[which(report_self_thinning$site=="BIA"& report_self_thinning$Model!="ORCHIDEE"),]$duration)

#max(report_self_thinning[which(report_self_thinning$site=="FIN" & report_self_thinning$Model!="ORCHIDEE"),]$duration)


report_self_thinning <-merge(manual_adjustment,collect_final,by.x=c("models_avail","site"), by.y=c("Mname","site"))
report_self_thinning$co2 <- NULL
report_self_thinning$Self_thinning_duration <- report_self_thinning$upper - report_self_thinning$lower
names(report_self_thinning) <- c("Model","site","upper","lower","mort_mech","id_method","slope","intercept","duration")
knitr::kable(report_self_thinning[,c("Model","site","lower","upper","duration","id_method","slope")], caption="overview of method applied to identify self-thinning period. 1)from self-thinning-related mortality above 95th percentile of that mortality rate, 2) from total mortality above 95th percentile of total mortality rate, 3) automatic adjustment: selection of the consecutive points between the furthest to the bottom-left and the topright points in the timeseries in self-thining space, replicating the self-thinning trajectory. 4) manual adjustment: start and end were selected manually by eyeballing the points in self-thinning space and selecting those points that replicate the most a  self-thinning trajectory; STslope= self-thinning slope values. STint = self-thinning intercept values.",digits=2)

```

